export const LAUNCHPAD_DEFINITIONS = [
  {
    id: 'pumpfun',
    name: 'Pump.fun',
    chain: 'Solana',
    category: 'Memecoin launchpad',
    logo: '/assets/img/platforms/pump.fun.webp',
    feeSlugs: ['pump.fun'],
    metricsFallback: { fees24h: 1991448, fees7d: 10142664, fees30d: 37297765, revenue24h: 1524633, revenue7d: 7758219, revenue30d: 28536656, asOf: '2026-08-20T09:21:00Z', source: 'DeFiLlama' },
    categoryId: 'pump-fun',
    categoryUrl: 'https://www.coingecko.com/en/categories/pump-fun',
    officialUrl: 'https://pump.fun/',
    nativeToken: {
      id: 'pump-fun', symbol: 'PUMP', relationship: 'native', chain: 'solana',
      contract: 'pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn',
    },
    excludeProjectIds: ['pump-fun', 'dogwifcoin'],
    verifiedCoinIds: ['pippin', 'fartcoin', 'the-black-bull', 'would', 'comedian'],
    verifiedLaunches: [
      { id: 'pippin', name: 'pippin', symbol: 'PIPPIN', chain: 'solana', contract: 'Dfh5DzRgSvvCFDoYc2ciTkMrbDfRKybA4SoFbPmApump' },
      { id: 'fartcoin', name: 'Fartcoin', symbol: 'FARTCOIN', chain: 'solana', contract: '9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump' },
      { id: 'the-black-bull', name: 'The Black Bull', symbol: 'ANSEM', chain: 'solana', contract: '9cRCn9rGT8V2imeM2BaKs13yhMEais3ruM3rPvTGpump' },
      { id: 'would', name: 'would', symbol: 'WOULD', chain: 'solana', contract: 'J1Wpmugrooj1yMyQKrdZ2vwRXG5rhfx3vTnYE39gpump' },
      { id: 'comedian', name: 'Comedian', symbol: 'BAN', chain: 'solana', contract: '9PR7nCP9DpcUotnDPVLUBUZKu5WAYkwrCUx9wDnSpump' },
    ],
    provenanceMode: 'category',
  },
  {
    id: 'pons',
    name: 'Pons',
    chain: 'Robinhood Chain',
    category: 'Token launchpad',
    logo: '/assets/img/platforms/pons.webp',
    feeSlugs: ['pons-v1', 'pons-v2'],
    metricsFallback: { fees24h: 308437, fees7d: 2854222, fees30d: 19407757, revenue24h: 65936, revenue7d: 587160, revenue30d: 5021954, asOf: '2026-08-20T09:21:00Z', source: 'DeFiLlama' },
    categoryId: 'pons-launchpad',
    categoryUrl: 'https://www.coingecko.com/en/categories/pons-launchpad',
    officialUrl: 'https://robinhood.ponslaunchpad.com/',
    docsUrl: 'https://docs.ponsfamily.com/',
    nativeToken: {
      id: 'pons', symbol: 'PONS', relationship: 'native', chain: 'robinhood',
      contract: '0x39dBED3a2bd333467115dE45665cC57F813C4571',
    },
    excludeProjectIds: ['pons'],
    verifiedCoinIds: ['thinking-cat', 'yolo-2', 'nasdanq', 'wire-bot'],
    verifiedLaunches: [
      { id: 'thinking-cat', name: 'Thinking Cat', symbol: 'HMM', chain: 'robinhood', contract: '0x7fe995a80075df3dc8ae11a9b82c7fe4202cd87f' },
      { id: 'yolo-2', name: 'YOLO', symbol: 'YOLO', chain: 'robinhood', contract: '0x62c71cd34a52c30d894419cbcc55db2afa8032ea' },
      { id: 'nasdanq', name: 'NASDANQ', symbol: 'NASDANQ', chain: 'robinhood', contract: '0x51fb76be80ab6daaa345d818f4e06441816b4fea' },
      { id: 'wire-bot', name: 'wire bot', symbol: 'WIRE', chain: 'robinhood', contract: '0x8ecea3d0e648db646d824aa51eedeb16ac3d6878' },
    ],
    provenanceMode: 'category',
  },
  {
    id: 'virtuals',
    name: 'Virtuals Protocol',
    chain: 'Multi-chain',
    category: 'AI-agent launchpad',
    logo: '/assets/img/platforms/virtuals-protocol.webp',
    feeSlugs: ['virtuals-protocol'],
    metricsFallback: { fees24h: 27117, fees7d: 96981, fees30d: 895836, revenue24h: 27117, revenue7d: 96981, revenue30d: 895836, asOf: '2026-08-20T09:21:00Z', source: 'DeFiLlama' },
    categoryId: 'virtuals-protocol-ecosystem',
    categoryUrl: 'https://www.coingecko.com/en/categories/virtuals-protocol-ecosystem',
    officialUrl: 'https://app.virtuals.io/',
    nativeToken: {
      id: 'virtual-protocol', symbol: 'VIRTUAL', relationship: 'native', chain: 'base',
      contract: '0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b',
    },
    excludeProjectIds: ['virtual-protocol'],
    provenanceMode: 'allowlist',
    verifiedCoinIds: [
      'ribbita-by-virtuals',
      'robo-token-2',
      'aixbt',
      'luna-by-virtuals',
      'game-by-virtuals',
      'vaderai-by-virtuals',
      'sekoia-by-virtuals',
      'wai-combinator-by-virtuals',
      'seraph-by-virtuals',
    ],
    verifiedLaunches: [
      { id: 'ribbita-by-virtuals', name: 'Ribbita by Virtuals', symbol: 'TIBBIR', chain: 'base', contract: '0xa4a2e2ca3fbfe21aed83471d28b6f65a233c6e00' },
      { id: 'robo-token-2', name: 'Fabric Protocol', symbol: 'ROBO', chain: 'base', contract: '0x407a5fb66cb1b3d50004f7091c08a27b42ba6d6f' },
      { id: 'aixbt', name: 'aixbt', symbol: 'AIXBT', chain: 'base', contract: '0x4f9fd6be4a90f2620860d680c0d4d5fb53d1a825' },
      { id: 'luna-by-virtuals', name: 'Luna by Virtuals', symbol: 'LUNA', chain: 'base', contract: '0x55cd6469f597452b5a7536e2cd98fde4c1247ee4' },
      { id: 'game-by-virtuals', name: 'GAME by Virtuals', symbol: 'GAME', chain: 'base', contract: '0x1c4cca7c5db003824208adda61bd749e55f463a3' },
      { id: 'vaderai-by-virtuals', name: 'Vader', symbol: 'VADER', chain: 'base', contract: '0x731814e491571a2e9ee3c5b1f7f3b962ee8f4870' },
      { id: 'sekoia-by-virtuals', name: 'sekoia by Virtuals', symbol: 'SEKOIA', chain: 'base', contract: '0x1185cb5122edad199bdbc0cbd7a0457e448f23c7' },
      { id: 'wai-combinator-by-virtuals', name: 'WAI Combinator by Virtuals', symbol: 'WAI', chain: 'base', contract: '0x6112b8714221bbd96ae0a0032a683e38b475d06c' },
      { id: 'seraph-by-virtuals', name: 'Seraph by Virtuals', symbol: 'SERAPH', chain: 'base', contract: '0x4f81837c2f4a189a0b69370027cc2627d93785b4' },
    ],
  },
  {
    id: 'fourmeme',
    name: 'Four.meme',
    chain: 'BNB Chain',
    category: 'Memecoin launchpad',
    logo: '/assets/img/platforms/four.meme.webp',
    feeSlugs: ['four.meme'],
    metricsFallback: { fees24h: 7687, fees7d: 97520, fees30d: 685767, revenue24h: 7558, revenue7d: 96742, revenue30d: 682717, asOf: '2026-08-20T09:21:00Z', source: 'DeFiLlama' },
    categoryId: 'four-meme-ecosystem',
    categoryUrl: 'https://www.coingecko.com/en/categories/four-meme-ecosystem',
    officialUrl: 'https://four.meme/',
    nativeToken: null,
    excludeProjectIds: [],
    verifiedCoinIds: ['bianrensheng', 'siren-2', 'lobster-2', 'tutorial'],
    verifiedLaunches: [
      { id: 'bianrensheng', name: '币安人生 (BinanceLife)', symbol: '币安人生', chain: 'bsc', contract: '0x924fa68a0fc644485b8df8abfa0a41c2e7744444' },
      { id: 'siren-2', name: 'Siren', symbol: 'SIREN', chain: 'bsc', contract: '0x997a58129890bbda032231a52ed1ddc845fc18e1' },
      { id: 'lobster-2', name: '龙虾 (Lobster)', symbol: '龙虾', chain: 'bsc', contract: '0xeccbb861c0dda7efd964010085488b69317e4444' },
      { id: 'tutorial', name: 'Tutorial', symbol: 'TUT', chain: 'bsc', contract: '0xcaae2a2f939f51d97cdfa9a86e79e3f085b799f3' },
    ],
    provenanceMode: 'category',
  },
  {
    id: 'bags',
    name: 'Bags',
    chain: 'Solana',
    category: 'Creator launchpad',
    logo: 'https://bags.fm/icon.png?e952db43040dbe33',
    feeSlugs: ['bags'],
    metricsFallback: { fees24h: 12515, fees7d: 141889, fees30d: 358452, revenue24h: 6256, revenue7d: 70919, revenue30d: 178446, asOf: '2026-08-20T09:21:00Z', source: 'DeFiLlama' },
    categoryId: 'bagsapp-ecosystem',
    categoryUrl: 'https://www.coingecko.com/en/categories/bagsapp-ecosystem',
    officialUrl: 'https://bags.fm/',
    nativeToken: null,
    excludeProjectIds: [],
    verifiedCoinIds: [
      'asteroid-the-space-shiba-inu',
      'p0-systems',
      'orynth',
      'holdflow',
      'x402-singularity-layer',
    ],
    verifiedLaunches: [
      { id: 'asteroid-the-space-shiba-inu', name: 'Asteroid The Space Shiba Inu', symbol: 'ASTEROID', chain: 'solana', contract: '4UeLCRqARmfb6e6KQijtiktqqXUxbfk6jZng7DhuBAGS' },
      { id: 'p0-systems', name: 'p0 Systems', symbol: 'P0', chain: 'solana', contract: 'HmTi3CQfKfXWbn1tNoiAxH7GzMV7L3tDAmPWabZEBAGS' },
      { id: 'orynth', name: 'Orynth', symbol: 'ORY', chain: 'solana', contract: 'FBaQqJAuYkuKQpAcDuHtuupSPpqi33fbTxKXSjLDQory' },
      { id: 'holdflow', name: 'HoldFlow', symbol: 'HOLD', chain: 'solana', contract: 'Es4RvTdJNyJZ3iCDvQ2vnd1QhB49dWB8Pug4kbrNBAGS' },
      { id: 'x402-singularity-layer', name: 'x402 Singularity Layer', symbol: 'SGL', chain: 'solana', contract: '5c4HyD2rSShqnTsf5z3SaoD2H3GE452u2CUuYjviBAGS' },
    ],
    provenanceMode: 'category',
  },
  {
    id: 'bonkfun',
    name: 'BONK.fun',
    chain: 'Solana',
    category: 'Memecoin launchpad',
    logo: '/assets/img/platforms/bonk.fun.webp',
    feeSlugs: ['bonk.fun-launchpad'],
    metricsFallback: { fees24h: 3487, fees7d: 23060, fees30d: 142629, revenue24h: 1984, revenue7d: 11885, revenue30d: 79309, asOf: '2026-08-20T09:21:00Z', source: 'DeFiLlama' },
    categoryId: 'letsbonk-fun-ecosystem',
    categoryUrl: 'https://www.coingecko.com/en/categories/letsbonk-fun-ecosystem',
    officialUrl: 'https://letsbonk.fun/',
    nativeToken: {
      id: 'bonk', symbol: 'BONK', relationship: 'ecosystem', chain: 'solana',
      contract: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
    },
    excludeProjectIds: ['bonk'],
    verifiedCoinIds: ['useless-3', 'fih', 'kori'],
    verifiedLaunches: [
      { id: 'useless-3', name: 'Useless Coin', symbol: 'USELESS', chain: 'solana', contract: 'Dz9mQ9NzkBcCsuGPFJ3r1bS4wgqKMHBPiVuniW8Mbonk' },
      { id: 'fih', name: 'fih', symbol: 'FIH', chain: 'solana', contract: '8SkfuQkYNTskoQUbbjr2JbZQeqQV9egnJXgfMXf5bonk' },
      { id: 'kori', name: 'Kori', symbol: 'KORI', chain: 'solana', contract: 'HtTYHz1Kf3rrQo6AqDLmss7gq5WrkWAaXn3tupUZbonk' },
    ],
    provenanceMode: 'category',
  },
  {
    id: 'ansemio',
    name: 'Ansem.io',
    chain: 'Solana',
    category: 'Pump.fun launch layer',
    logo: '/assets/img/platforms/ansem.ico',
    feeSlugs: [],
    categoryId: null,
    categoryUrl: null,
    officialUrl: 'https://ansem.io/',
    docsUrl: 'https://ansem.io/leaderboard',
    docsLabel: 'Leaderboard',
    researchSources: [
      { label: 'Launch mechanism', url: 'https://www.kucoin.com/news/flash/ansem-launches-platform-for-token-teams-to-buy-his-attention-via-airdrops' },
    ],
    nativeToken: {
      id: 'the-black-bull', symbol: 'ANSEM', relationship: 'ecosystem', chain: 'solana',
      contract: '9cRCn9rGT8V2imeM2BaKs13yhMEais3ruM3rPvTGpump',
    },
    excludeProjectIds: ['the-black-bull'],
    verifiedCoinIds: ['ansem-bulls-eye', 'ansem-z'],
    verifiedLaunches: [
      {
        id: 'ansem-bulls-eye', name: "BULLS'S EYE", symbol: 'EYE', chain: 'solana',
        contract: 'RmtMAYVTTFv2iK9muMrXEoAnSSsZPPgRPbqZCKwNDYk',
        source: 'https://ansem.io/launch/coin/RmtMAYVTTFv2iK9muMrXEoAnSSsZPPgRPbqZCKwNDYk',
      },
      {
        id: 'ansem-z', name: 'Z', symbol: 'Z', chain: 'solana',
        contract: '7MQSupJTpY31HGChEHUAsS1pQhLSrHS5CCsB9bnaN3eS',
        source: 'https://ansem.io/launch/coin/7MQSupJTpY31HGChEHUAsS1pQhLSrHS5CCsB9bnaN3eS',
      },
    ],
    provenanceMode: 'official-contract-page',
    alwaysDisplay: true,
    rankingStatus: 'unranked',
    note: 'Ansem.io launches through Pump.fun and adds on-chain airdrop, burn, and attention mechanics. DeFiLlama does not currently index separate Ansem.io fees.',
  },
];
