export const LAUNCHPAD_DEFINITIONS = [
  {
    id: 'pumpfun',
    name: 'Pump.fun',
    chain: 'Solana',
    category: 'Memecoin launchpad',
    logo: '/assets/img/platforms/pump.fun.webp',
    feeSlugs: ['pump.fun'],
    categoryId: 'pump-fun',
    categoryUrl: 'https://www.coingecko.com/en/categories/pump-fun',
    officialUrl: 'https://pump.fun/',
    nativeToken: { id: 'pump-fun', symbol: 'PUMP', relationship: 'native' },
    excludeProjectIds: ['pump-fun', 'dogwifcoin'],
    verifiedCoinIds: ['pippin', 'fartcoin', 'the-black-bull', 'would', 'comedian'],
    provenanceMode: 'category',
  },
  {
    id: 'pons',
    name: 'Pons',
    chain: 'Robinhood Chain',
    category: 'Token launchpad',
    logo: '/assets/img/platforms/pons.webp',
    feeSlugs: ['pons-v1', 'pons-v2'],
    categoryId: 'pons-launchpad',
    categoryUrl: 'https://www.coingecko.com/en/categories/pons-launchpad',
    officialUrl: 'https://robinhood.ponslaunchpad.com/',
    docsUrl: 'https://docs.ponsfamily.com/',
    nativeToken: { id: 'pons', symbol: 'PONS', relationship: 'native' },
    excludeProjectIds: ['pons'],
    verifiedCoinIds: ['thinking-cat', 'yolo-2', 'nasdanq', 'wire-bot'],
    provenanceMode: 'category',
  },
  {
    id: 'virtuals',
    name: 'Virtuals Protocol',
    chain: 'Multi-chain',
    category: 'AI-agent launchpad',
    logo: '/assets/img/platforms/virtuals-protocol.webp',
    feeSlugs: ['virtuals-protocol'],
    categoryId: 'virtuals-protocol-ecosystem',
    categoryUrl: 'https://www.coingecko.com/en/categories/virtuals-protocol-ecosystem',
    officialUrl: 'https://app.virtuals.io/',
    nativeToken: { id: 'virtual-protocol', symbol: 'VIRTUAL', relationship: 'native' },
    excludeProjectIds: ['virtual-protocol'],
    provenanceMode: 'allowlist',
    verifiedCoinIds: [
      'ribbita-by-virtuals',
      'robo-token-2',
      'aixbt',
      'luna-by-virtuals',
      'game-by-virtuals',
      'vaderai-by-virtuals',
      'sekoia-by-virtuals',
      'wai-combinator-by-virtuals',
      'seraph-by-virtuals',
    ],
  },
  {
    id: 'fourmeme',
    name: 'Four.meme',
    chain: 'BNB Chain',
    category: 'Memecoin launchpad',
    logo: '/assets/img/platforms/four.meme.webp',
    feeSlugs: ['four.meme'],
    categoryId: 'four-meme-ecosystem',
    categoryUrl: 'https://www.coingecko.com/en/categories/four-meme-ecosystem',
    officialUrl: 'https://four.meme/',
    nativeToken: null,
    excludeProjectIds: [],
    verifiedCoinIds: ['bianrensheng', 'siren-2', 'lobster-2', 'tutorial'],
    provenanceMode: 'category',
  },
  {
    id: 'bags',
    name: 'Bags',
    chain: 'Solana',
    category: 'Creator launchpad',
    logo: 'https://bags.fm/icon.png?e952db43040dbe33',
    feeSlugs: ['bags'],
    categoryId: 'bagsapp-ecosystem',
    categoryUrl: 'https://www.coingecko.com/en/categories/bagsapp-ecosystem',
    officialUrl: 'https://bags.fm/',
    nativeToken: null,
    excludeProjectIds: [],
    verifiedCoinIds: [
      'asteroid-the-space-shiba-inu',
      'p0-systems',
      'orynth',
      'holdflow',
      'x402-singularity-layer',
    ],
    provenanceMode: 'category',
  },
  {
    id: 'bonkfun',
    name: 'BONK.fun',
    chain: 'Solana',
    category: 'Memecoin launchpad',
    logo: '/assets/img/platforms/bonk.fun.webp',
    feeSlugs: ['bonk.fun-launchpad'],
    categoryId: 'letsbonk-fun-ecosystem',
    categoryUrl: 'https://www.coingecko.com/en/categories/letsbonk-fun-ecosystem',
    officialUrl: 'https://letsbonk.fun/',
    nativeToken: { id: 'bonk', symbol: 'BONK', relationship: 'ecosystem' },
    excludeProjectIds: ['bonk'],
    verifiedCoinIds: ['useless-3', 'fih', 'kori'],
    provenanceMode: 'category',
  },
];
